### PR TITLE
Introduced bug: hl instead of h1 on about:line 11

### PR DESCRIPTION
**Pull request by tapiwamla**
Used hl instead of h1 for the main heading tag

### CODE REVIEW

**Comment by chidozhou** [comment]
Indentify where the bug is note the commit hash. Use git log

**Comment by tapiwamla** [comment]
The commit hash is: 417cefd77f9deb67bee15e1758d08a727d627f59

**Comment by chidozhou** [comment]
I will revert the commit and let you rectify

**Comment by chidozhou** [comment]
Can you revert it from your end and make the changes

**Comment by tapiwamla** [comment]
Done. Reverted and hl is now h1. You can close.

**Pull request merged**
